blueprint:
  name: Timed backup
  description: Creates a backup at the given time pattern
  author: Dany Khalife
  domain: automation
  input:
    hours:
      description: Hours portion of the time pattern
      selector:
        text:
      default: 0
    minutes:
      description: Minutes portion of the time pattern
      selector:
        text:
      default: 0
    seconds:
      description: Seconds portion of the time pattern
      selector:
        text:
      default: 0

mode: single
trigger:
  - platform: time_pattern
    hours: !input hours
    minutes: !input minutes
    seconds: !input seconds
action:
  - action: backup.create
